# Generated by Django 3.0.8 on 2020-09-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0003_auto_20200906_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_brand',
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
